default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST") { 'localhost' } %>
  timeout: 5000
  variables:
    sql_mode: traditional

development:
  <<: *default
  username: exercism_v3
  password: exercism_v3
  database: exercism_v3_development

test:
  <<: *default
  username: exercism_v3
  password: exercism_v3
  database: exercism_v3_test

production:
  <<: *default
  database:
  host:
  username:
  password:
